#!/bin/bash

# ===============================================
# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
# build-scripts and precompiled standalone toolchains for Raspberry Pi.

# Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ===============================================

# This script auto-deploys CI compiled Cross & Native GCC Toolchain binaries to Sourceforge secured server

BASE_URL="sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers"

function deploy_file() {
    local FOLDER="$1"
    local FILEPATH="$2"
    local SUBFOLDER="$3"
    
    if [ -f "$FILEPATH" ]; then
        URL="$BASE_URL/$FOLDER/$SUBFOLDER"
        URL=$(printf "%s\n" "$URL" | sed 's/ /%20/g')
        curl -k "$URL" -u "$USER_SFTP:$PASSWORD_SFTP" -T "$FILEPATH" --ftp-create-dirs
    else
        echo "Cannot find $FILEPATH"
    fi
}

TitleCaseConverter() {
    echo "$1" | sed 's/./\L&/; s/^./\u&/'
}

RPIOS_TYPE="$(TitleCaseConverter "$RPIOS_TYPE")"

# Set FOLDER based on conditions
if [ "$RPI_TYPE" = "64" ]; then
    if [ "$BASE" = "true" ]; then
        FOLDER="CLI Base/64/$RPIOS_TYPE/GCC $GCC_VERSION"
    else
        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains/$RPIOS_TYPE/GCC $GCC_VERSION"
    fi
    SUBFOLDER=""
else
    if [ "$BASE" = "true" ]; then
        FOLDER="CLI Base/$RPIOS_TYPE/GCC $GCC_VERSION"
    else
        FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/$RPIOS_TYPE/GCC $GCC_VERSION"
    fi
    case "$RPI_TYPE" in
        "0-1") SUBFOLDER="Raspberry Pi 1, Zero/" ;;
        "2-3") SUBFOLDER="Raspberry Pi 2, 3/" ;;
        "3+")  SUBFOLDER="Raspberry Pi 3A+, 3B+, 4, 5/" ;;
    esac
fi

# Deploy Cross-compiler Toolchain binaries
FILEPATH="$HOME/cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz"
deploy_file "$FOLDER" "$FILEPATH" "$SUBFOLDER"

# Deploy Native-compiler Toolchain binaries
if [ "$RPI_TYPE" = "64" ]; then
    FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains/$RPIOS_TYPE/GCC $GCC_VERSION"
    SUBFOLDER=""
else
    FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/$RPIOS_TYPE/GCC $GCC_VERSION"
fi

FILEPATH="$HOME/native-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz"
deploy_file "$FOLDER" "$FILEPATH" "$SUBFOLDER"

# Deploy Desktop-compiler Toolchain binaries
FILEPATH="$HOME/desktop-gcc-$GCC_VERSION-pi_$OS_TYPE.tar.gz"
FOLDER="Exclusive-Experimental Toolchains/Desktop/$OS_TYPE/GCC $GCC_VERSION"
deploy_file "$FOLDER" "$FILEPATH" ""